### ISSUE TITLE
How to build the RCN from your article?

### ISSUE THREAD

**Issue by Cadene** [manoja328/tallyqacode#1]
Hi @manoja328,

Thanks for releasing this code :)
Unfortunately, I don't see any README. Do you have any advice one should know before trying your main.py? I would like to reproduce your best results from your article.

Is your best one RN_OG_embd? https://github.com/manoja328/tallyqacode/blob/master/main.py#L18

Best regards!

**Comment by manoja328** [comment]
I updated instructions in the repo. Please, Let me know if you have questions.

**Comment by Cadene** [comment]
Thanks :)
